spring:
  profiles:
    active: default
  application:
    name: Crawler-Parser

  couchbase:
    connection-string: couchbase://127.0.0.1
    username: crawler
    password: crawler
    bucket-name: crawler-bucket

kafka:
  bootstrapAddress: localhost:9092
  urlEventTopic: CRW_TOPIC_NEW_URL
  consumerGroup: DEFAULT_NEW_URL_CS_GROUP

logging:
  level: {org.pradeesh.crawler.parser: debug}

